logging:
  level:
    ar.org.cecba: TRACE
    org.springframework: INFO
    org.apache.catalina.webresources.Cache: ERROR
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/linktracker
    password: admin
    username: postgres
    hikari:
      maximum-pool-size: 50
      minimum-idle: 2
      idle-timeout: 60000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
server:
  protocol: 'http:'
  domain: 'localhost:8080'
  subdomain: 'l'